services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    environment:
      - EULA=TRUE
      - VERSION=1.20.6
      - TYPE=PAPER
      - MEMORY=4G
    volumes:
      - ./data:/data
    ports:
      - "25565:25565"
    restart: unless-stopped
